
Description: This template creates DynamoDB tables and two S3 buckets
Metadata:
  'AWS::CloudFormation::Designer':
    96a88428-7b68-408e-9a44-9d6da9803624:
      size:
        width: 60
        height: 60
      position:
        x: 115.00570379278906
        'y': 85.01705140525644
      z: 0
      embeds: []
    f80c4bac-fd09-4e7e-a7ef-f332a22d7a4a:
      size:
        width: 60
        height: 60
      position:
        x: 240
        'y': 90
      z: 0
      embeds: []
    c83dcf6a-a51f-4ed4-a0fb-679fce7b1b22:
      size:
        width: 60
        height: 60
      position:
        x: 360
        'y': 90
      z: 0
      embeds: []
    a70db5c7-00b4-43c6-82f6-b6977e4aa072:
      size:
        width: 60
        height: 60
      position:
        x: 490
        'y': 90
      z: 0
      embeds: []
    b2207b26-56d7-4600-aece-5f4defe6aa90:
      size:
        width: 60
        height: 60
      position:
        x: 230
        'y': 200
      z: 0
      embeds: []
    5430aeb8-6a0d-48f9-9ba7-fcb1e13c31f0:
      size:
        width: 60
        height: 60
      position:
        x: 351.00570379278906
        'y': 201.01705140525644
      z: 0
      embeds: []
Parameters:
  TagName:
    Type: String
    Default: OpsAutomatorTaskList
    MinLength: 1
    MaxLength: 127
    Description: >-
      Default name of tag that contains the list of tasks for a tagged
      resources.
  EnableTaskCleanup:
    Type: String
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'Yes'
    Description: Enable cleanup of task tracking table.
  RetainFailedTasks:
    Type: String
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'Yes'
    Description: Do not delete failed tasks.
  SendAnonymousData:
    Type: String
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'Yes'
    Description: Send Anonymous Metrics Data.
  TaskRetentionHours:
    Type: Number
    MinValue: 1
    Default: 168
    Description: Number of hours after which tasks are deleted..
  LogRetentionDays:
    Type: Number
    Default: 30
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
      - 120
      - 150
      - 180
      - 365
      - 400
      - 545
      - 731
      - 1827
      - 3653
    Description: Retention days for scheduler logs.
  LambdaSize:
    Type: Number
    Description: >-
      Lambda function size, increment size when processing large amounts of
      resources
    Default: 128
    AllowedValues:
      - 128
      - 192
      - 256
      - 320
      - 384
      - 448
      - 512
      - 576
      - 640
      - 704
      - 768
      - 832
      - 896
      - 960
      - 1024
      - 1088
      - 1152
      - 1216
      - 1280
      - 1344
      - 1408
      - 1472
      - 1536
      - 1600
      - 1664
      - 1728
      - 1792
      - 1856
      - 1920
      - 1984
      - 2048
      - 2112
      - 2176
      - 2240
      - 2304
      - 2368
      - 2432
      - 2496
      - 2560
      - 2624
      - 2688
      - 2752
      - 2816
      - 2880
      - 2944
      - 3008
  ConfigBackupDays:
    Type: Number
    Default: 30
    MinValue: 1
    Description: Retention days for scheduler configuration backups.
  SchedulerActive:
    Type: String
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'Yes'
    Description: Activate or deactivate scheduling of task.
Resources:
  ConcurrencyTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: ConcurrencyId
          AttributeType: S
      KeySchema:
        - AttributeName: ConcurrencyId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 96a88428-7b68-408e-9a44-9d6da9803624
  TaskTrackingTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
        - AttributeName: ConcurrencyId
          AttributeType: S
        - AttributeName: LastCompletionCheck
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      GlobalSecondaryIndexes:
        - IndexName: WaitForExecutionTasks
          KeySchema:
            - AttributeName: ConcurrencyId
              KeyType: HASH
            - AttributeName: Id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: '2'
            WriteCapacityUnits: '2'
        - IndexName: WaitForCompletionTasks
          KeySchema:
            - AttributeName: Id
              KeyType: HASH
            - AttributeName: LastCompletionCheck
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: '2'
            WriteCapacityUnits: '2'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: f80c4bac-fd09-4e7e-a7ef-f332a22d7a4a
  LastSchedulerExecutionTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: Name
          AttributeType: S
      KeySchema:
        - AttributeName: Name
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c83dcf6a-a51f-4ed4-a0fb-679fce7b1b22
  ConfigurationTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: Name
          AttributeType: S
      KeySchema:
        - AttributeName: Name
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 2
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
    Metadata:
      'AWS::CloudFormation::Designer':
        id: a70db5c7-00b4-43c6-82f6-b6977e4aa072
  Configuration:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: !Ref ConfigBackupDays
            Prefix: Backups/
            Status: Enabled
    Metadata:
      'AWS::CloudFormation::Designer':
        id: b2207b26-56d7-4600-aece-5f4defe6aa90
  TaskResources:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 5430aeb8-6a0d-48f9-9ba7-fcb1e13c31f0
Outputs:
  ConcurrencyTable:
    Description: Table ID for concurrency
    Value: !Sub '${ConcurrencyTable}'
  TaskTrackingTable:
    Description: Table ID for TaskTrackingTable
    Value: !Sub '${TaskTrackingTable}'
  LastSchedulerExecutionTable:
    Description: Table ID for LastSchedulerExecutionTable
    Value: !Sub '${LastSchedulerExecutionTable}'
  ConfigurationTable:
    Description: Table ID for ConfigurationTable
    Value: !Sub '${ConfigurationTable}'
  ConfigurationBucket:
    Description: Bucket identifier for ConfigurationBucket
    Value: !Sub '${Configuration}'
  TaskResources:
    Description: Bucket Identifier for TaskResources
    Value: !Sub '${TaskResources}'
  ConfigurationTableArn:
    Description: Arn of the ConfigurationTable
    Value: !Sub '${ConfigurationTable.Arn}'
  Configuration:
    Description: Bucket name for configuration
    Value: !Sub '${Configuration}'
  TaskTrackingTableArn:
    Description: Arn of the TaskTrackingTable
    Value: !Sub '${TaskTrackingTable.Arn}'
  TaskTrackingTableStreamArn:
    Description: Stream Arn
    Value: !GetAtt 
      - TaskTrackingTable
      - StreamArn
  ConfigurationTableStreamArn:
    Description: Stream Arn
    Value: !GetAtt 
      - ConfigurationTable
      - StreamArn
