
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Ops Automator, template version 1.1.2.34, (SO0029). Adapted from AWS Ops Automator template and categorised into different nested templates.
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Ops Automator (version 1.1.2.34)
        Parameters:
          - TagName
      - Label:
          default: Maintenance
        Parameters:
          - EnableTaskCleanup
          - RetainFailedTasks
          - SchedulerActive
          - TaskRetentionHours
          - LambdaSize
    ParameterLabels:
      EnableTaskCleanup:
        default: Cleanup Task Tracking Table
      RetainFailedTasks:
        default: Keep failed tasks
      SchedulerActive:
        default: Scheduling active
      TagName:
        default: Ops Automator Tagname
      TaskRetentionHours:
        default: Hours to keep tasks
      ConfigBackupDays:
        default: Days to keep configuration backups
      LambdaSize:
        default: Lambda size (MB)
      SendAnonymousData:
        default: Send anonymous usage data
  'AWS::CloudFormation::Designer':
    89452dad-6e13-48b5-95c2-22b4e80c81f1:
      size:
        width: 60
        height: 60
      position:
        x: 313.0057067871094
        'y': 86.01705169677734
      z: 0
      embeds: []
    4c4dff67-29f5-4510-8393-8becdeb54129:
      size:
        width: 60
        height: 60
      position:
        x: 500
        'y': 90
      z: 0
      embeds: []
      dependson:
        - 89452dad-6e13-48b5-95c2-22b4e80c81f1
    48793a8b-04d3-4b8a-9b0e-a72394e17f4a:
      size:
        width: 60
        height: 60
      position:
        x: 680
        'y': 90
      z: 0
      embeds: []
      dependson:
        - 4c4dff67-29f5-4510-8393-8becdeb54129
    17d7cc22-3b7e-4ab7-9965-7747cec8cecd:
      source:
        id: 4c4dff67-29f5-4510-8393-8becdeb54129
      target:
        id: 89452dad-6e13-48b5-95c2-22b4e80c81f1
      z: 11
    ebd8bee8-6a6d-4211-898e-f451cfeeacdf:
      source:
        id: 48793a8b-04d3-4b8a-9b0e-a72394e17f4a
      target:
        id: 4c4dff67-29f5-4510-8393-8becdeb54129
      z: 12
Conditions:
  EnableTaskCleanupCondition: !Equals 
    - !Ref EnableTaskCleanup
    - 'Yes'
  KeepFailedTasksCondition: !Equals 
    - !Ref RetainFailedTasks
    - 'Yes'
Mappings:
  EnabledDisabled:
    'Yes':
      Value: ENABLED
    'No':
      Value: DISABLED
  YesNoBoolean:
    'Yes':
      Value: 'True'
    'No':
      Value: 'False'
  Settings:
    Metrics:
      Url: 'https://metrics.awssolutionsbuilder.com/generic'
      SolutionId: S00029
    Resources:
      ResourceToS3SizeKB: 16
    DynamoDbTableCapacities:
      TrackingTableMinRead: 5
      TrackingTableMaxRead: 100
      TrackingTableMinWrite: 5
      TrackingTableMaxWrite: 100
      TrackingTableCompletionMinRead: 5
      TrackingTableCompletionMaxRead: 50
      TrackingTableCompletionMinWrite: 5
      TrackingTableCompletionMaxWrite: 50
      TrackingTableExecutionMinRead: 2
      TrackingTableExecutionMaxRead: 50
      TrackingTableExecutionMinWrite: 2
      TrackingTableExecutionMaxWrite: 50
      ConcurrencyTableMinRead: 2
      ConcurrencyTableMaxRead: 50
      ConcurrencyTableMinWrite: 2
      ConcurrencyTableMaxWrite: 50
      ConfigurationTableMinRead: 2
      ConfigurationTableMaxRead: 10
      ConfigurationTableMinWrite: 1
      ConfigurationTableMaxWrite: 5
      LastExecutionRead: 1
      LastExecutionWrite: 1
Parameters:
  TagName:
    Type: String
    Default: OpsAutomatorTaskList
    MinLength: 1
    MaxLength: 127
    Description: >-
      Default name of tag that contains the list of tasks for a tagged
      resources.
  EnableTaskCleanup:
    Type: String
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'Yes'
    Description: Enable cleanup of task tracking table.
  RetainFailedTasks:
    Type: String
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'Yes'
    Description: Do not delete failed tasks.
  SendAnonymousData:
    Type: String
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'Yes'
    Description: Send Anonymous Metrics Data.
  TaskRetentionHours:
    Type: Number
    MinValue: 1
    Default: 168
    Description: Number of hours after which tasks are deleted..
  LogRetentionDays:
    Type: Number
    Default: 30
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
      - 120
      - 150
      - 180
      - 365
      - 400
      - 545
      - 731
      - 1827
      - 3653
    Description: Retention days for scheduler logs.
  LambdaSize:
    Type: Number
    Description: >-
      Lambda function size, increment size when processing large amounts of
      resources
    Default: 128
    AllowedValues:
      - 128
      - 192
      - 256
      - 320
      - 384
      - 448
      - 512
      - 576
      - 640
      - 704
      - 768
      - 832
      - 896
      - 960
      - 1024
      - 1088
      - 1152
      - 1216
      - 1280
      - 1344
      - 1408
      - 1472
      - 1536
      - 1600
      - 1664
      - 1728
      - 1792
      - 1856
      - 1920
      - 1984
      - 2048
      - 2112
      - 2176
      - 2240
      - 2304
      - 2368
      - 2432
      - 2496
      - 2560
      - 2624
      - 2688
      - 2752
      - 2816
      - 2880
      - 2944
      - 3008
  ConfigBackupDays:
    Type: Number
    Default: 30
    MinValue: 1
    Description: Retention days for scheduler configuration backups.
  SchedulerActive:
    Type: String
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'Yes'
    Description: Activate or deactivate scheduling of task.
Resources:
  ddbtabless3template:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: >-
        https://s3-us-west-2.amazonaws.com/enquizit/Cloudformation/Task-13/ddbtabless3template.yaml
      Parameters:
        ConfigBackupDays: !Ref ConfigBackupDays
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 89452dad-6e13-48b5-95c2-22b4e80c81f1
  rolelambdatemplate:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: >-
        https://s3-us-west-2.amazonaws.com/enquizit/Cloudformation/Task-13/role-lambda-template.yaml
      Parameters:
        EnableTaskCleanup: !Ref EnableTaskCleanup
        RetainFailedTasks: !Ref RetainFailedTasks
        TaskTrackingTable: !GetAtt 
          - ddbtabless3template
          - Outputs.TaskTrackingTable
        ConfigurationTableStreamArn: !GetAtt 
          - ddbtabless3template
          - Outputs.ConfigurationTableStreamArn
        TaskTrackingTableStreamArn: !GetAtt 
          - ddbtabless3template
          - Outputs.TaskTrackingTableStreamArn
        LastSchedulerExecutionTable: !GetAtt 
          - ddbtabless3template
          - Outputs.LastSchedulerExecutionTable
        ConfigurationTable: !GetAtt 
          - ddbtabless3template
          - Outputs.ConfigurationTable
        TaskResources: !GetAtt 
          - ddbtabless3template
          - Outputs.TaskResources
        ConfigurationTableArn: !GetAtt 
          - ddbtabless3template
          - Outputs.ConfigurationTableArn
        ConcurrencyTable: !GetAtt 
          - ddbtabless3template
          - Outputs.ConcurrencyTable
        Configuration: !GetAtt 
          - ddbtabless3template
          - Outputs.Configuration
        TaskTrackingTableArn: !GetAtt 
          - ddbtabless3template
          - Outputs.TaskTrackingTableArn
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 4c4dff67-29f5-4510-8393-8becdeb54129
    DependsOn:
      - ddbtabless3template
  ApplicationAutoScalingtemplate:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: >-
        https://s3-us-west-2.amazonaws.com/enquizit/Cloudformation/Task-13/Applicationautoscaling-template.yaml
      Parameters:
        OpsAutomatorScalingRole: !GetAtt 
          - rolelambdatemplate
          - Outputs.OpsAutomatorScalingRole
        ConcurrencyTable: !GetAtt 
          - ddbtabless3template
          - Outputs.ConcurrencyTable
        TaskTrackingTable: !GetAtt 
          - ddbtabless3template
          - Outputs.TaskTrackingTable
        ConfigurationTable: !GetAtt 
          - ddbtabless3template
          - Outputs.ConfigurationTable
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 48793a8b-04d3-4b8a-9b0e-a72394e17f4a
    DependsOn:
      - rolelambdatemplate
